name: Hourly GeekNews Notifier

on:
  schedule:
    - cron: '0 * * * *' # 매 정시(1시간마다) 실행
  workflow_dispatch:    # 버튼 눌러서 수동 실행 가능하게 함

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install rss-parser axios

      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node index.js